version: '3.7'
services:

  db:
    image: postgres:14.2
    restart: always
    container_name: kadmos_demo_db
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - kadmos_default

  account-service-a:
    image: kadmos-demo/account-service
    container_name: service-a
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/kadmosdemo
      SPRING_ACTIVE_PROFILE: service-a
    networks:
      - kadmos_default

  account-service-b:
    image: kadmos-demo/account-service
    container_name: service-b
    depends_on:
      - db
    ports:
      - "8082:8082"
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/kadmosdemo
      SPRING_ACTIVE_PROFILE: service-b
    networks:
      - kadmos_default

  gateway:
    image: kadmos-demo/gateway
    container_name: gateway
    depends_on:
      - account-service-a
      - account-service-b
    ports:
      - "8080:8080"
    environment:
      SERVICE_A_BASE_URI: http://account-service-a:8081
      SERVICE_B_BASE_URI: http://account-service-b:8082
    networks:
        - kadmos_default
volumes:
  db:
    driver: local

networks:
  kadmos_default:
    name: kadmos_default