version: '3.7'
services:

  db:
    image: postgres:14.2
    restart: always
    container_name: kadmos_demo_db
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
