spring:
  application:
    name: gateway-service
  management:
    endpoints:
      web:
        exposure:
          include: "*"

  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
        wiretap: true
      httpserver:
        wiretap: true

gateway:
  services:
    service-a:
      gatewayPath: /savings/a/balance
      methods:
        - GET
        - POST
      baseUri: localhost:${wiremock.server.port}
      routingPath: /balance
    service-b:
      gatewayPath: /savings/b/balance
      methods:
        - GET
        - POST
      baseUri: localhost:${wiremock.server.port}
      routingPath: /balance
