spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kadmosdemo
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    default-schema: main

logging:
  level:
    root: INFO
